---
title: "Iteration and Listcols"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
set.seed(12345)
```


### Lists

```{r}
vec_numeric = 5:8
vec_char = c("My", "name", "is", "laylah")

tibble(
  num = vec_numeric,
  char = vec_char
)

vec_logical = c(TRUE, TRUE, TRUE, FALSE)
```


Different stuff with different lengths

```{r}
l = list(
  vec_numeric = 5:8,
  vec_char = LETTERS,
  mat         = matrix(1:8, 2, 4),
  vec_logical = c(TRUE, FALSE),
  summary     = summary(rnorm(1000)))
l
```


Accessing lists

```{r}
l$vec_numeric

l[[1]]

l[[1]][1:3]
```

### for loops

```{r}
list_norms = 
  list(
    a = rnorm(20, 3, 1),
    b = rnorm(20, 0, 5),
    c = rnorm(20, 10, .2),
    d = rnorm(20, -3, 1)
  )

is.list(list_norms)
```

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```

```{r}
mean_and_sd(list_norms[[1]])

mean_and_sd(list_norms[[2]])

mean_and_sd(list_norms[[3]])

mean_and_sd(list_norms[[4]])
```

```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = mean_and_sd(list_norms[[i]])
}
```


### use `map`

```{r}
output = map(list_norms, mean_and_sd)

output = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = median(list_norms[[i]])
}

output = map(list_norms, median)
```


### Create DF

```{r}
 listcol_df = 
  tibble(
    name = c("a", "b", "c", "d"),
    samp = list_norms
  )
```

```{r}
listcol_df |> pull(name)

listcol_df |> pull(samp)

mean_and_sd(listcol_df$samp[[1]])
mean_and_sd(listcol_df$samp[[2]])
mean_and_sd(listcol_df$samp[[3]])

map(listcol_df$samp, mean_and_sd)

listcol_df |> 
  mutate(
    mean_sd = map(samp, mean_and_sd),
    median = map(samp, median)) |> 
  select(name, mean_sd) |> 
  unnest(mean_sd)
```


### NSDUH Data

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = read_html(nsduh_url)
```

Import Function

```{r}
nsduh_import = function(html, table_number, outcome_name) {
  
  html |> 
  html_table() |> 
  nth(table_number) |>
  slice(-1) |> 
  select(-contains("P Value")) |>
  pivot_longer(
    -State,
    names_to = "age_year", 
    values_to = "percent") |>
  separate(age_year, into = c("age", "year"), sep = "\\(") |>
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_replace(percent, "[a-c]$", ""),
    percent = as.numeric(percent),
    outcome = outcome_name) |>
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
  
}

nsduh_import(html = nsduh_html, 1, "marj")
nsduh_import(html = nsduh_html, 4, "cocaine")
nsduh_import(html = nsduh_html, 5, "heroine")
```

Import data using a for loop

```{r}
table_input = list(1, 4, 5)
name_input = list("marj", "cocaine", "heroine")

output = vector("list", 3)

for (i in 1:3) {
  output[[i]] = nsduh_import(nsduh_html, table_input[[i]], name_input[[i]])
}

nsduh_df = bind_rows(output)
```


Try again, using maps!!!

```{r}
nsduh_import = function(html, table_number) {
  
  html |> 
  html_table() |> 
  nth(table_number) |>
  slice(-1) |> 
  select(-contains("P Value")) |>
  pivot_longer(
    -State,
    names_to = "age_year", 
    values_to = "percent") |>
  separate(age_year, into = c("age", "year"), sep = "\\(") |>
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_replace(percent, "[a-c]$", ""),
    percent = as.numeric(percent)) |> 
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
  
}


nsduh_df = 
  tibble(
    name = c("marj", "cocaine", "heroine"),
    number = c(1, 4, 5)) |> 
  mutate(
    table = map(number, nsduh_import, html = nsduh_html)) |> 
  unnest(table)

map(nsduh_df$number, nsduh_import, html = nsduh_html)
```


### Revisit weather df

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```


```{r}
weather_df
```

